sudo: required
services:
- docker
language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
stages:
- flow
- lint
- test
- name: docker
  if: branch = master AND env(TRAVIS_PULL_REQUEST) = false
jobs:
  include:
  - stage: flow
    script: npm run flow
  - stage: lint
    script: npm run linter:js
  - script: npm run linter:css
  - stage: test
    script: npm test -- --coverage --maxWorkers=4
    after_script: cat coverage/lcov.info | node_modules/.bin/coveralls
  - stage: docker
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build . --tag $DOCKER_REGISTRY/$REPO
    - docker push $DOCKER_REGISTRY/$REPO
env:
  global:
  - secure: aylAuiHt7knn6FvTYVEF1vVwn4yp7tGTE5XlBdHQV4VMesIRVhaofF6vhIQvloJD8YdlQXAe4Q6Q/5k6OMCNbt6W1FzN9KiKD5X1uFsqTHxB0UUD2trugoy8tb2fvPgRMJb5YdLxDTlklnBseRkrbAeuusJBRWMrfa0i0/n+hixtTRVRDIDBk6VsDAWK6Q3Lefvh7DWBDu+up6yVPbEB2VyuSudPk271lWRC2A7gm8Ks+j1EmgvDz+DFBrk1QS5NfEfR9m++ksx5jN39AKKW7ff/2pVkP3YP2J53EqUTJ/39yBprrJcIoxDtOl/JKBvKP/MWHtl8bTFOVvOxKtfhySpOnuTTJK6vyvqhTn6cQCzEqX5TRovuN7EdGwEnCTN9K3v2iHDm5vkCcPX1GoPswKnlhDCe6+zwALn64zEztBZBYHc0SuEtOkiLQDC45z8/pubmZxCjfprnhSdQNePwxWQlWqcogF/IkyT/FiysINAS4A9gizq8VN8hVWdC98tVW29x6FrBH/B7A3ahtYVIt4zg7o0EAZaGYpMytcsdZlyNwZ7cuAlAXa944vl4i/WRYFz3HBp/B3PCiHNku2oLTFR2nz0AYMQBQmAGhmFM6l3gYZLeKIoJ1aQIl95uOBuk6ypfVMORdgUyp2rA/Djg52gUu8C4+N0uB+9T4Umno90=
  - secure: fVtDlzdDUuNYj2FRFpsfjZqd6yK0m0bbPkEhPHwm3P8zcY01R2S7yAjCp5imjiTnu7Q+2SiJ0S0ZCTt3+38esSBmT7DDLsqbjzPLPxssSINx3sjiOn4zatbJ0l5l6QyMfkar0ccC1RgvO1dlHPF6skFs0K6v7YdXwayyfkdkCwzTBq9Yw54N8/hG2V5HIT9SxNCsRJf4Wc7bNNsvKX+YZd+VtF4dEg5q9Bb78gsvBLGz5GFbsguNgiQUsqtlSI2II/ldG4Ha/q8KKvmbu+krZx14uTmAKizI4fY37nAQKGGDbhRQnFjjtsDycdsv3ZakgVbrl4rwMBymulbWMLZEYmxANpgR1RtWy+lWU3ik0njueUta/jOQf6GTsf7nBkT4GASRVWp/VmdwPpbSGKmdL3S22/H8ptwJhduSI5EV4gNTZK3g1NYn+3B6d7RKRqHQUeJ5FYPAcF/+9O7d5+D3Q8W++B0543wDuvjA5t543ZEPb0mzA2awXlFd3Tp6V5/n9h0Y5OANxVOeYngZcogRqk8Hs/Mj/pfACRwH3N/DT8BPbfrmP7SZ14PhC8Eis5BfbsWumbg2pCNiw56XtclraDXRhlmJwBR4kFNQ5Fb4DsddgiGeypRVSzYjCsanzDZyQjcZmzwYfR5aMkUm8+Y5s5TUdebu+N2M9Lz1pqKh8VQ=
  - secure: f34LMGflq97LJtPR2LLGU5crZptnofv9sia8tLbduRspfQlWoDCBAe2PEn9oukAzRZw14XgdnLF/2Gb8KrZpJfqtPBrteS0sRxZwdYqy/xRXGMhwPPMLFWtFmS1c1QYkzxsNvSK24YrnCI9u7K9iNecnXsPuQ8yD1wtuhTOLnRZ2XnnKvxze6ePKxFaEAGKuf7DMXKcutKC0B8GnQfOtMaRdi/A4vdjo/7zEanNDpVMR3LCpCSmDZ4tLnH39gXCBiP5BL2BwcYCenT7KRNl1blNuRH3sNcf+KieLTVa887/mK7hjuKkEyKg5J5X4bAt3uqBch31gULHSICmZYSdrKJzh2cHq5aGWcxaWx02M0GlXx9SmXjcIHzJjHmJCyEWGf3J2SkQCRZq6vUlWTn5FWuZZnCDKYnbnXUfb7qbwpAFQ+xfvu5vppXTOLPZwMVo1veopCwvA0+T0XI7W4HU5YuMeCBKgOgucNKJeKptn3U+jgX0qeAYV4RON6G42or7VlCSFO51Mbyx3IwXnVwDqTY9inaxb0K1FdP/cdZVUTZOSQWJJy16a1Qo9IXnfqi+zA4F3Y/RbL2SMGpi4yhAz64JKnxj6WmqT6N6hS5OAlFpqkA4uONDre9l/rfKomPBQh6mw6u8dxTyi8Qh+f+T6oQeYNc3cYiD6eGAbfwjhFf8=
  - secure: MOPhX1Qmrq2of0Xw8xm8Yk44Gb12G7AtcJlAItlvGvWaGmjm3WEH4a5jAhkPBflsTedMCv7ot7ylfOogpJTtNUx9cOM6Lrr5xA2fsi9L4ybgTbtgrtF+rcCX+vId3chDaey2HRdN0ruAqH5HpjvyvVpaksW9mTEkWLmpWdxzAQfmZ65VzU8ziiQSu4m9gSmr6ENjWHekT9R6PZsY4oA3rdwK8kdq0fDpY4qdRbu0NLDGpRW47O0iErmB8Yw4NEx5XpUp5Nqkh5wOIZvPAeGOV5PUfrkzr2OeotybEELKUwdVf9bm3nQYD/RjhYel30bNQejmGw580TFFcYAiBJgGf9mj/VffpRkheJgh8qi9wKascbOSpLTfa0YGsnfYFuw+qeQDp7L5XuHBqhCtkoPbgYmwK0hoUyK8HS/o71pI00waYpzM43tFbHIwrqLRE/s3EoALMz5iPBiqK/KwJ7tqg2fhDUZR/6YgwGa/+z/fU9N16dX7/rBXh1++Wru8qhxb27xUMh/nA7ymbD+2qIq6y7XF05s0lCEbBLKZDjVLT97YDcuEIchU/n9BJCQbD5StdeanPPeMMSIN7RKJOPYE9K6vOb7b1zysOfNQ8DBOYuk8GajgJzQ7Xd3WPO0wy19Qu93ppTeDi859uc7C1yjsGbte1I47zc9CA9JFznm31G4=
addons:
  ssh_known_hosts:
    secure: RoYuLa2laPcWVWUPWg6QkFeKahb+dBRnHg3O5/O92uL/zX7MlQ2Nnw1h38zdzsslD1fsVHsxKdM9FG42FPqTRRHrhGTfjMMAa73FbtpArPJBRCqjDd47VcSJdRkFAoOXwhxhda2GAjlkTY6MeN3KKkAYwkwx1Wnp1Gg8OzsTdwlgXYzrIu3RBy5D/KD9/5XtyMFUwAw6t86UyiZmzCQsh9Ie8l/yCGZF6krPjHcWDUP/fKOvsXQ2wshM7f7932r+HM/KxrDYO0cMuXdV7H6eWhCp1gKE7IQfyq+W+0SngzGnH1WSVUOveDAmYo4QYvHLD9Nw4ba62zCETlaBVd1rwlHQN9QjMsJZMGtsLRhGYR1PHp/grpJJRhI8GTB1asUxfkzBhUDr/XoSELc1Jd1wKYAsSMS1gxe65kBbevfqJp/oK/b7RFCKg6MpnR1uRhiDH0e7Yrhr44NPyvqAvf7yFiYg/tF4LivAzINMxEYpj9ESVGIJanOaUbOfmfcKkgeckty5bf8z/KLfq8PfzuqjolwRdVVMgRHIHGWHzlCa+x6J8mpz7/iUX9iIz5+87ACDXczV6fY8AC3ZequWBGPIVPlN8jZ11wXyE4k62Q+m2cLSJF3DpWhSICYJSz8H525ITLpKCsMPCNQZBOn04X/QGIYBhE0B7yt5GB3GjS3qyAY=
